### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by arnov** [KeesCBakker/dutch-pluralizer-py#2]
When using python 3.6 this crashes on a reggex module import.

```
    from dutch_pluralizer import singularize
../../../.pyenv/versions/3.6.9/envs/transformers/lib/python3.6/site-packages/dutch_pluralizer/__init__.py:9: in <module>
    from .pluralizer import pluralize, pluralize_advanced
../../../.pyenv/versions/3.6.9/envs/transformers/lib/python3.6/site-packages/dutch_pluralizer/pluralizer.py:10: in <module>
    from .strategies.pluralize_bastard_words import pluralize_bastard
../../../.pyenv/versions/3.6.9/envs/transformers/lib/python3.6/site-packages/dutch_pluralizer/strategies/pluralize_bastard_words.py:3: in <module>
    from .helpers import VOWELS
../../../.pyenv/versions/3.6.9/envs/transformers/lib/python3.6/site-packages/dutch_pluralizer/strategies/helpers.py:2: in <module>
    from re import Pattern
E   ImportError: cannot import name 'Pattern'
```

**Comment by KeesCBakker** [comment]
The package was developed using Python 3.8 and I think it was compatible with 3.7 -- let me take a look to see how easy it is to get it working under 3.6.

**Comment by KeesCBakker** [comment]
Looks like it only has to do with a type hint for `Pattern`. Removed the type hint and the tests for 3.6 work. Currently publishing a new version of the packages to PyPI.

**Comment by KeesCBakker** [comment]
Pushed out `0.0.39`, can you check if that one works for your setup? https://pypi.org/project/dutch-pluralizer/0.0.39/

**Comment by arnov** [comment]
Awesome, thanks for the quick response, will try tomorrow!

BTW you might also want to merge some code to master, because now I was a bit confused by the seemingly empty repo (but everything is in a branch)

**Comment by arnov** [comment]
Seems to work perfectly, thanks again 😎
